### ISSUE TITLE
Impossible to login (css is displayed)

### ISSUE THREAD

**Issue by quentinberder** [codebutler/foursquarex#44]
When I log in I get an alert window with the following code (I am using the FoursquareX "FoursquareX-0.10" and Mac OS X 10.6.8);

``` css
<html>
<head>
  <title>foursquare</title>
<style type="text/css">
body, html {
  border: 0px;
  padding: 0px;
  margin: 0px;
  background-color: #f1f1f1;
  font-family:helvetica,arial,sans-serif;
}
img.displayed {
  display: block;
  margin-left: auto;
  margin-right: auto
}
#container {
  position:relative;
  float:left;
  left: 50%;
  margin-left: -525px;
}
a {
  font-size: 22px;
  text-decoration: none;
  color: #0cbadf;
}

h1, h2 {
  padding: 0px;
  margin: 0px;
  text-decoration: none;
  width: 479px;
}

h1 {
  color:#999999;
  font-size:40px;
  left:170px;
  position:absolute;
  top:173px;
}
h2 {
  position: absolute;
  top: 282px;
  left: 170px;
  color: #999999;
}

input {
  border:1px solid #999999;
  color:#666666;
  font-size:13px;
  padding:5px 10px;
  width:292px;
  height: 30px;

  -moz-border-radius: 5px;
  -webkit-border-radius: 5px;
  border-radius: 5px;
}

form {
  margin-top: 5px;
}

#logo {
  color:#f1f1f1;
  left:79px;
  position:absolute;
  top:18px;
}

.newgreenbutton {
background: #a7e300;
background: -webkit-gradient(linear, left top, left bottom, from(#a7e300), to(#99d100));
background: -moz-linear-gradient(top,  #a7e300,  #99d100);
filter: progid:dximagetransform.microsoft.gradient(startcolorstr='#a7e300', endcolorstr='#99d100');
border: 1px solid #87b800;
color: #fff;
cursor: pointer;
font-family: "helvetica neue", helvetica, arial, sans-serif;
font-size: 11px;
font-weight: bold;
height: 30px;
line-height: 30px;
padding: 0 10px;
text-align: center;
text-shadow: rgba(0,0,0,.1) 0 -1px 0;
text-transform: uppercase;
-moz-border-radius: 5px;
-webkit-border-radius: 5px;
border-radius: 5px;
}

.newgreenbutton:hover {
background: #b2eb14;
background: -webkit-gradient(linear, left top, left bottom, from(#b2eb14), to(#a4da14));
background: -moz-linear-gradient(top,  #b2eb14,  #a4da14);
filter: progid:dximagetransform.microsoft.gradient(startcolorstr='#b2eb14', endcolorstr='#a4da14');
}
.newgreenbutton:active {
background: #99d100;
background: -webkit-gradient(linear, left top, left bottom, from(#99d100), to(#a7e300));
background: -moz-linear-gradient(top,  #99d100,  #a7e300);
filter: progid:dximagetransform.microsoft.gradient(startcolorstr='#99d100', endcolorstr='#a7e300');
}


</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js" type="text/javascript"></script>

</head>
<body>
  <div id="container" class="translate">
    <a id="logo" href="https://foursquare.com"><img src="https://playfoursquare.s3.amazonaws.com/misc/logo.jpg" /></a>
    <img src="https://playfoursquare.s3.amazonaws.com/misc/404.jpg" class="displayed" alt="not found" />
    <h1>we couldn't find the page<br />
        you're looking for</h1>

    <h2>search for users, venues, or tips<br />
        <form action="https://foursquare.com/search" method="get">
          <input type="text" autocomplete="off" name="q">
          <button name="submit" class="newgreenbutton" type="submit">search</button>
        </form></h2>
  </div>
  <script src="https://www.google-analytics.com/ga.js" type="text/javascript"/>
  <script type="text/javascript">
    try {
      var pagetracker = _gat._gettracker('ua-2322480-5');
      pagetracker._trackpageview('/404');
    } catch(err) {}
  </script>
</body>
</html>
```
